### ISSUE TITLE
Test all worlds before R2021b release

### ISSUE THREAD

**Issue by stefaniapedrazzi** [cyberbotics/webots#3251]
For R2021b it is important to test again all the distributed worlds.
Given that they are a lot, I split the 294 + webots-projects worlds in 5 blocks of about 60 worlds that will be assigned to different developers.

Block 1:
* [x] 1/294: ~webots/projects/humans/rigged_humans/worlds/city.wbt~ not found
* [x] 2/294: ~webots/projects/humans/rigged_humans/worlds/humans.wbt~ not found
* [x] 3/294: webots/projects/humans/pedestrian/worlds/pedestrian.wbt
* [x] 4/294: webots/projects/humans/c3d/worlds/c3d_viewer.wbt
* [x] 5/294: webots/projects/languages/matlab/worlds/e-puck_matlab.wbt
* [x] 6/294: webots/projects/languages/cpp/worlds/example.wbt
* [x] 7/294: webots/projects/languages/java/worlds/example.wbt
* [x] 8/294: webots/projects/languages/python/worlds/example.wbt
* [x] 9/294: webots/projects/vehicles/worlds/city_traffic.wbt **crashes webots**
* [x] 10/294: webots/projects/vehicles/worlds/city.wbt
* [x] 11/294: webots/projects/vehicles/worlds/highway.wbt **crashes webots**
* [x] 12/294: ~webots/projects/vehicles/worlds/city_A.wbt~ not found
* [x] 13/294: webots/projects/vehicles/worlds/CH_Vens.wbt **Error opening https://raw.githubusercontent.com/cyberbotics/webots/R2021b/projects/objects/buildings/protos/textures/old_brick_wall.jpg**  Fixed in #3308.
* [x] 14/294: webots/projects/vehicles/worlds/boomer.wbt
* [x] 15/294: webots/projects/vehicles/worlds/CH_Morges.wbt
* [x] 16/294: webots/projects/vehicles/worlds/sumo_interface_example.wbt **crashes webots**
* [x] 17/294: webots/projects/vehicles/worlds/highway_overtake.wbt **crashes webots**
* [x] 18/294: webots/projects/vehicles/worlds/village_winter.wbt **Error opening https://raw.githubusercontent.com/cyberbotics/webots/R2021b/projects/objects/buildings/protos/textures/red_brick_wall.jpg** Fixed in #3308.
* [x] 19/294: webots/projects/vehicles/worlds/village.wbt **Error opening https://raw.githubusercontent.com/cyberbotics/webots/R2021b/projects/objects/buildings/protos/textures/old_brick_wall.jpg** Fixed in #3308.
* [x] 20/294: webots/projects/vehicles/worlds/city_night.wbt
* [x] 21/294: webots/projects/vehicles/worlds/village_center.wbt
* [x] 22/294: webots/projects/vehicles/worlds/village_realistic.wbt
* [x] 23/294: webots/projects/samples/mybot/worlds/mybot.wbt
* [x] 24/294: webots/projects/samples/mybot/worlds/mybot_physics.wbt
* [x] 25/294: webots/projects/samples/mybot/worlds/mybot_camera.wbt
* [x] 26/294: webots/projects/samples/geometries/worlds/textured_proto_shapes.wbt
* [x] 27/294: webots/projects/samples/geometries/worlds/extended_solids.wbt
* [x] 28/294: webots/projects/samples/geometries/worlds/geometric_primitives.wbt
* [x] 29/294: webots/projects/samples/geometries/worlds/floating_geometries.wbt
* [x] 30/294: webots/projects/samples/geometries/worlds/polygons.wbt
* [x] 31/294: webots/projects/samples/geometries/worlds/physics_primitives.wbt
* [x] 32/294: webots/projects/samples/geometries/worlds/webots_box.wbt
* [x] 33/294: webots/projects/samples/geometries/worlds/extrusion.wbt
* [x] 34/294: webots/projects/samples/geometries/worlds/textured_boxes.wbt
* [x] 35/294: webots/projects/samples/geometries/worlds/high_resolution_indexedfaceset.wbt
* [x] 36/294: webots/projects/samples/geometries/worlds/textured_shapes.wbt
* [x] 37/294: webots/projects/samples/geometries/worlds/muscle.wbt
* [x] 38/294: webots/projects/samples/devices/worlds/coupled_motors.wbt
* [x] 39/294: webots/projects/samples/devices/worlds/range_finder.wbt
* [x] 40/294: webots/projects/samples/devices/worlds/camera_noise_mask.wbt
* [x] 41/294: webots/projects/samples/devices/worlds/camera_motion_blur.wbt
* [x] 42/294: webots/projects/samples/devices/worlds/track.wbt
* [x] 43/294: webots/projects/samples/devices/worlds/propeller.wbt
* [x] 44/294: webots/projects/samples/devices/worlds/position_sensor.wbt
* [x] 45/294: webots/projects/samples/devices/worlds/light_sensor.wbt
* [x] 46/294: webots/projects/samples/devices/worlds/motor2.wbt
* [x] 47/294: webots/projects/samples/devices/worlds/sick_point_cloud.wbt
* [x] 48/294: webots/projects/samples/devices/worlds/emitter_receiver.wbt
* [x] 49/294: webots/projects/samples/devices/worlds/supervisor.wbt
* [x] 50/294: webots/projects/samples/devices/worlds/gps.wbt
* [x] 51/294: webots/projects/samples/devices/worlds/camera_segmentation.wbt
* [x] 52/294: webots/projects/samples/devices/worlds/hinge_joint_with_backlash.wbt
* [x] 53/294: webots/projects/samples/devices/worlds/camera_recognition.wbt
* [x] 54/294: webots/projects/samples/devices/worlds/speaker_text_to_speech.wbt
* [x] 55/294: webots/projects/samples/devices/worlds/accelerometer.wbt
* [x] 56/294: webots/projects/samples/devices/worlds/camera_auto_focus.wbt
* [x] 57/294: webots/projects/samples/devices/worlds/pen.wbt
* [x] 58/294: webots/projects/samples/devices/worlds/speaker.wbt
* [x] 59/294: webots/projects/samples/devices/worlds/brake.wbt
* [x] 60/294: webots/projects/samples/devices/worlds/encoders.wbt

Block 2:
* [x] 61/294: webots/projects/samples/devices/worlds/force3d_sensor.wbt
* [x] 62/294: webots/projects/samples/devices/worlds/motor3.wbt
* [x] 63/294: webots/projects/samples/devices/worlds/bumper.wbt
* [x] 64/294: webots/projects/samples/devices/worlds/linear_motor.wbt
* [x] 65/294: webots/projects/samples/devices/worlds/radar.wbt
* [x] 66/294: webots/projects/samples/devices/worlds/distance_sensor.wbt
* [x] 67/294: webots/projects/samples/devices/worlds/motor.wbt
* [x] 68/294: webots/projects/samples/devices/worlds/spherical_camera.wbt
* [x] 69/294: webots/projects/samples/devices/worlds/hinge_2_joint_with_backlash.wbt
* [x] 70/294: webots/projects/samples/devices/worlds/sick.wbt
* [x] 71/294: webots/projects/samples/devices/worlds/gps_lat_long.wbt
* [x] 72/294: webots/projects/samples/devices/worlds/connector.wbt
* [x] 73/294: webots/projects/samples/devices/worlds/battery.wbt
* [x] 74/294: webots/projects/samples/devices/worlds/force_sensor.wbt
* [x] 75/294: webots/projects/samples/devices/worlds/camera.wbt
* [x] 76/294: webots/projects/samples/devices/worlds/hokuyo.wbt
* [x] 77/294: webots/projects/samples/devices/worlds/inertial_unit.wbt
* [x] 78/294: webots/projects/samples/devices/worlds/lidar.wbt
* [x] 79/294: webots/projects/samples/devices/worlds/laser_pointer.wbt
* [x] 80/294: webots/projects/samples/devices/worlds/receiver_noise.wbt
* [x] 81/294: webots/projects/samples/devices/worlds/led.wbt
* [x] 82/294: webots/projects/samples/devices/worlds/display.wbt
* [x] 83/294: webots/projects/samples/devices/worlds/gyro.wbt
* [x] 84/294: webots/projects/samples/devices/worlds/compass.wbt
* [x] 85/294: webots/projects/samples/rendering/worlds/animated_skin.wbt
* [x] 86/294: webots/projects/samples/rendering/worlds/sponza.wbt
* [x] 87/294: webots/projects/samples/rendering/worlds/physically_based_rendering.wbt
* [x] 88/294: webots/projects/samples/curriculum/worlds/beginner_move_your_e-puck.wbt
* [x] 89/294: webots/projects/samples/curriculum/worlds/beginner_rally.wbt
* [x] 90/294: webots/projects/samples/curriculum/worlds/intermediate_oam.wbt
* [x] 91/294: webots/projects/samples/curriculum/worlds/novice_accelerometer.wbt
* [x] 92/294: webots/projects/samples/curriculum/worlds/advanced_odometry.wbt
* [x] 93/294: webots/projects/samples/curriculum/worlds/intermediate_lfm.wbt
* [x] 94/294: webots/projects/samples/curriculum/worlds/novice_motors.wbt
* [x] 95/294: webots/projects/samples/curriculum/worlds/novice_remain_in_shadow.wbt
* [x] 96/294: webots/projects/samples/curriculum/worlds/advanced_particle_swarm_optimization.wbt
* [x] 97/294: webots/projects/samples/curriculum/worlds/advanced_slam.wbt
* [x] 98/294: webots/projects/samples/curriculum/worlds/intermediate_lawn_mower.wbt
* [x] 99/294: webots/projects/samples/curriculum/worlds/advanced_pattern_recognition.wbt
* [x] 100/294: webots/projects/samples/curriculum/worlds/intermediate_behavior_based.wbt
* [x] 101/294: webots/projects/samples/curriculum/worlds/novice_k2000.wbt
* [x] 102/294: webots/projects/samples/curriculum/worlds/beginner_finite_state_machine.wbt
* [x] 103/294: webots/projects/samples/curriculum/worlds/beginner_linear_camera.wbt
* [x] 104/294: webots/projects/samples/curriculum/worlds/advanced_genetic_algorithm.wbt
* [x] 105/294: webots/projects/samples/curriculum/worlds/beginner_blinking_e-puck.wbt
* [x] 106/294: webots/projects/samples/curriculum/worlds/beginner_e-puck_dance.wbt
* [x] 107/294: webots/projects/samples/curriculum/worlds/novice_train.wbt
* [x] 108/294: webots/projects/samples/curriculum/worlds/beginner_better_collision_avoidance_algorithm.wbt
* [x] 109/294: webots/projects/samples/curriculum/worlds/novice_camera.wbt
* [x] 110/294: webots/projects/samples/curriculum/worlds/beginner_robot_controller.wbt
* [x] 111/294: webots/projects/samples/curriculum/worlds/advanced_path_planning.wbt
* [x] 112/294: webots/projects/samples/curriculum/worlds/intermediate_finite_state_machine.wbt
* [x] 113/294: webots/projects/samples/curriculum/worlds/novice_ir_sensors.wbt
* [x] 114/294: webots/projects/samples/curriculum/worlds/novice_linear_camera.wbt
* [x] 115/294: webots/projects/samples/robotbenchmark/maze_runner/worlds/maze_runner.wbt
* [x] 116/294: webots/projects/samples/robotbenchmark/visual_tracking/worlds/visual_tracking.wbt
* [x] 117/294: webots/projects/samples/robotbenchmark/humanoid_marathon/worlds/humanoid_marathon.wbt **WARNING: DEF ENVIRONMENT Solid > SignPole (PROTO) > DirectionPanel (PROTO) > Transform > DEF FRONT_SIDE Shape > PBRAppearance > ImageTexture: 'textures/panel_hbp_office_front.png' not found.** Fixed in #3306.
* [x] 118/294: webots/projects/samples/robotbenchmark/inverted_pendulum/worlds/inverted_pendulum.wbt
* [x] 119/294: webots/projects/samples/robotbenchmark/humanoid_sprint/worlds/humanoid_sprint.wbt
* [x] 120/294: webots/projects/samples/robotbenchmark/robot_programming/worlds/robot_programming.wbt

Block 3:
* [x] 121/294: webots/projects/samples/robotbenchmark/wall_following/worlds/wall_following.wbt https://github.com/cyberbotics/webots/issues/3326#issue-936754784
* [x] 122/294: highway_driving.wbt https://github.com/cyberbotics/webots/issues/3327
* [x] 123/294: webots/projects/samples/robotbenchmark/pick_and_place/worlds/pick_and_place.wbt https://github.com/cyberbotics/webots/issues/3326#issue-936754784
* [x] 124/294: webots/projects/samples/robotbenchmark/obstacle_avoidance/worlds/obstacle_avoidance.wbt  https://github.com/cyberbotics/webots/issues/3326#issue-936754784
* [x] 125/294: webots/projects/samples/robotbenchmark/pit_escape/worlds/pit_escape.wbt https://github.com/cyberbotics/webots/issues/3326#issue-936754784
* [x] 126/294: webots/projects/samples/robotbenchmark/square_path/worlds/square_path.wbt https://github.com/cyberbotics/webots/issues/3326#issue-936754784
* [x] 127/294: webots/projects/samples/tutorials/worlds/collision_avoidance.wbt
* [x] 128/294: webots/projects/samples/tutorials/worlds/4_wheels_robot.wbt
* [x] 129/294: webots/projects/samples/tutorials/worlds/appearance.wbt
* [x] 130/294: webots/projects/samples/tutorials/worlds/my_first_simulation.wbt
* [x] 131/294: webots/projects/samples/tutorials/worlds/compound_solid.wbt
* [x] 132/294: webots/projects/samples/tutorials/worlds/obstacles.wbt
* [x] 133/294: webots/projects/samples/howto/enu_coordinate_system/worlds/enu_coordinate_system.wbt https://github.com/cyberbotics/webots/issues/3329
* [x] 134/294: webots/projects/samples/howto/console/worlds/console.wbt https://github.com/cyberbotics/webots/issues/3329
* [x] 135/294: webots/projects/samples/howto/four_wheels/worlds/four_wheels.wbt
* [x] 136/294: webots/projects/samples/howto/vision/worlds/vision.wbt
* [x] 137/294: webots/projects/samples/howto/mouse_events/worlds/mouse_events.wbt
* [x] 138/294: webots/projects/samples/howto/gears/worlds/gears.wbt https://github.com/cyberbotics/webots/issues/3330
* [x] 139/294: webots/projects/samples/howto/inverted_pendulum/worlds/inverted_pendulum.wbt https://github.com/cyberbotics/webots/issues/3331
* [x] 140/294: webots/projects/samples/howto/physics/worlds/physics.wbt
* [x] 141/294: webots/projects/samples/howto/binocular/worlds/binocular.wbt
* [x] 142/294: webots/projects/samples/howto/custom_robot_window_simple/worlds/custom_robot_window_simple.wbt https://github.com/cyberbotics/webots/issues/3332
* [x] 143/294: webots/projects/samples/howto/ziegler_nichols/worlds/ziegler_nichols.wbt
* [x] 144/294: webots/projects/samples/howto/force_control/worlds/force_control.wbt
* [x] 145/294: webots/projects/samples/howto/pedal_racer/worlds/pedal_racer.wbt
* [x] 146/294: webots/projects/samples/howto/openai_gym/worlds/openai_gym.wbt
* [x] 147/294: webots/projects/samples/howto/passive_dynamic_walker/worlds/passive_dynamic_walker.wbt
* [x] 148/294: webots/projects/samples/howto/sick_terrain_scanning/worlds/sick_terrain_scanning.wbt
* [x] 149/294: webots/projects/samples/howto/url/worlds/url.wbt
* [x] 150/294: webots/projects/samples/howto/asymmetric_friction/worlds/asymmetric_friction1.wbt
* [x] 151/294: webots/projects/samples/howto/asymmetric_friction/worlds/asymmetric_friction2.wbt
* [x] 152/294: webots/projects/samples/howto/rope/worlds/rope.wbt
* [x] 153/294: webots/projects/samples/howto/omni_wheels/worlds/omni_wheels.wbt
* [x] 154/294: webots/projects/samples/howto/custom_robot_window/worlds/custom_robot_window.wbt
* [x] 155/294: webots/projects/samples/howto/cylinder_stack/worlds/cylinder_stack.wbt
* [x] 156/294: webots/projects/samples/howto/texture_change/worlds/texture_change.wbt https://github.com/cyberbotics/webots/issues/3333
* [x] 157/294: webots/projects/samples/howto/spinning_top/worlds/spinning_top.wbt
* [x] 158/294: webots/projects/samples/howto/supervisor_draw_trail/worlds/supervisor_draw_trail.wbt
* [x] 159/294: webots/projects/samples/howto/center_of_mass/worlds/center_of_mass.wbt
* [x] 160/294: webots/projects/samples/howto/biped/worlds/biped.wbt
* [x] 161/294: webots/projects/samples/demos/worlds/hexapod.wbt
* [x] 162/294: webots/projects/samples/demos/worlds/anaglyph.wbt
* [x] 163/294: webots/projects/samples/demos/worlds/gantry.wbt
* [x] 164/294: webots/projects/samples/demos/worlds/moon.wbt
* [x] 165/294: webots/projects/samples/demos/worlds/soccer.wbt
* [x] 166/294: webots/projects/samples/demos/worlds/stewart_platform.wbt
* [x] 167/294: webots/projects/samples/environments/factory/worlds/hall.wbt
* [x] 168/294: webots/projects/samples/environments/factory/worlds/factory.wbt
* [x] 169/294: webots/projects/samples/environments/indoor/worlds/complete_apartment.wbt
* [x] 170/294: webots/projects/samples/environments/indoor/worlds/kitchen.wbt
* [x] 171/294: webots/projects/samples/environments/indoor/worlds/apartment.wbt
* [x] 172/294: webots/projects/samples/environments/indoor/worlds/break_room.wbt
* [x] 173/294: webots/projects/samples/contests/tower_of_hanoi/worlds/tower_of_hanoi.wbt
* [x] 174/294: webots/projects/samples/contests/robocup/worlds/kid.wbt
* [x] 175/294: webots/projects/samples/contests/robocup/worlds/adult.wbt
* [x] 176/294: webots/projects/samples/contests/rockin/worlds/work.wbt
* [x] 177/294: webots/projects/samples/contests/rockin/worlds/home.wbt
* [x] 178/294: webots/projects/samples/contests/ratslife/worlds/ratslife_round.wbt https://github.com/cyberbotics/webots/issues/3336
* [x] 179/294: webots/projects/samples/contests/ratslife/worlds/ratslife.wbt
* [x] 180/294: webots/projects/robots/kuka/youbot/worlds/youbot_matlab.wbt <-- tested

Block 4:
* [x] 181/294: webots/projects/robots/kuka/youbot/worlds/youbot.wbt
* [x] 182/294: webots/projects/robots/mir/mir100/worlds/mir100.wbt
* [x] 183/294: webots/projects/robots/gctronic/e-puck/worlds/e-puck.wbt
* [x] 184/294: webots/projects/robots/gctronic/e-puck/worlds/e-puck2_pi-puck.wbt
* [x] 185/294: webots/projects/robots/gctronic/e-puck/worlds/e-puck2_server.wbt
* [x] 186/294: webots/projects/robots/gctronic/e-puck/worlds/e-puck_botstudio.wbt
* [x] 187/294: webots/projects/robots/gctronic/e-puck/worlds/e-puck2.wbt
* [x] 188/294: webots/projects/robots/gctronic/e-puck/worlds/e-puck_line_demo.wbt
* [x] 189/294: webots/projects/robots/gctronic/e-puck/worlds/e-puck_botstudio_with_floor_sensors.wbt
* [x] 190/294: webots/projects/robots/gctronic/e-puck/worlds/e-puck_cross-compilation.wbt
* [x] 191/294: webots/projects/robots/gctronic/e-puck/worlds/e-puck_kinematic.wbt
* [x] 192/294: webots/projects/robots/gctronic/e-puck/worlds/e-puck_line.wbt
* [x] 193/294: webots/projects/robots/gctronic/elisa/worlds/elisa3.wbt
* [x] 194/294: webots/projects/robots/pal_robotics/tiago_titanium/worlds/tiago_titanium.wbt
* [x] 195/294: webots/projects/robots/pal_robotics/tiago_base/worlds/tiago_base.wbt
* [x] 196/294: webots/projects/robots/pal_robotics/tiago++/worlds/tiago++.wbt
* [x] 197/294: webots/projects/robots/pal_robotics/tiago_steel/worlds/tiago_steel.wbt
* [x] 198/294: webots/projects/robots/pal_robotics/tiago_iron/worlds/tiago_iron.wbt
* [x] 199/294: webots/projects/robots/softbank/nao/worlds/get_the_candies.wbt https://github.com/cyberbotics/webots/issues/3265#issuecomment-872991040
* [x] 200/294: webots/projects/robots/softbank/nao/worlds/challenge.wbt
* [x] 201/294: webots/projects/robots/softbank/nao/worlds/nao_demo.wbt
* [x] 202/294: webots/projects/robots/softbank/nao/worlds/robotstadium_nao_vs_robotis-op2.wbt https://github.com/cyberbotics/webots/issues/3287#issuecomment-872906344
* [x] 203/294: webots/projects/robots/softbank/nao/worlds/nao_room.wbt
* [x] 204/294: webots/projects/robots/softbank/nao/worlds/nao_matlab.wbt <--- tested
* [x] 205/294: webots/projects/robots/softbank/nao/worlds/nao_indoors.wbt
* [x] 206/294: webots/projects/robots/softbank/nao/worlds/nao_robocup.wbt https://github.com/cyberbotics/webots/issues/3287#issuecomment-872906344
* [x] 207/294: webots/projects/robots/sony/aibo/worlds/aibo_ers7.wbt
* [x] 208/294: webots/projects/robots/sony/qrio/worlds/qrio.wbt
* [x] 209/294: webots/projects/robots/robotcub/icub/worlds/icub_stand.wbt
* [x] 210/294: webots/projects/robots/festo/robotino3/worlds/robotino3.wbt
* [x] 211/294: webots/projects/robots/adept/pioneer2/worlds/pioneer2.wbt
* [x] 212/294: webots/projects/robots/adept/pioneer3/worlds/pioneer3dx_gripper.wbt
* [x] 213/294: webots/projects/robots/adept/pioneer3/worlds/pioneer3dx_matlab.wbt <--- tested
* [x] 214/294: webots/projects/robots/adept/pioneer3/worlds/pioneer3dx_with_kinect.wbt
* [x] 215/294: webots/projects/robots/adept/pioneer3/worlds/pioneer3at.wbt
* [x] 216/294: webots/projects/robots/adept/pioneer3/worlds/pioneer3dx_collision_avoidance.wbt
* [x] 217/294: webots/projects/robots/adept/pioneer3/worlds/pioneer3dx.wbt
* [x] 218/294: webots/projects/robots/micromagic/mantis/worlds/mantis.wbt https://github.com/cyberbotics/webots/issues/3283
* [x] 219/294: webots/projects/robots/micromagic/scout/worlds/scout.wbt
* [x] 220/294: webots/projects/robots/kinematics/tinkerbots/worlds/android_l30.wbt
* [x] 221/294: webots/projects/robots/kinematics/tinkerbots/worlds/donnergugi.wbt
* [x] 222/294: webots/projects/robots/kinematics/tinkerbots/worlds/tinkerbots_demo.wbt
* [x] 223/294: webots/projects/robots/kinematics/tinkerbots/worlds/roadster.wbt
* [x] 224/294: webots/projects/robots/kinematics/tinkerbots/worlds/braitenberg.wbt https://github.com/cyberbotics/webots/issues/3309
* [x] 225/294: webots/projects/robots/kinematics/tinkerbots/worlds/sensoric_mega_set.wbt
* [x] 226/294: webots/projects/robots/kinematics/tinkerbots/worlds/racer.wbt
* [x] 227/294: webots/projects/robots/kinematics/tinkerbots/worlds/top_dog.wbt
* [x] 228/294: webots/projects/robots/kinematics/tinkerbots/worlds/grabber_base.wbt
* [x] 229/294: webots/projects/robots/kinematics/tinkerbots/worlds/vision_car.wbt https://github.com/cyberbotics/webots/issues/3309
* [x] ~230/294: webots/projects/robots/kinematics/tinkerbots/worlds/tinkerbots_demo_A.wbt~ not found
* [x] 231/294: webots/projects/robots/bluebotics/shrimp/worlds/shrimp.wbt
* [x] 232/294: webots/projects/robots/nex/worlds/fire_bird_6_remote_control.wbt
* [x] 233/294: webots/projects/robots/nex/worlds/fire_bird_6.wbt
* [x] 234/294: webots/projects/robots/nvidia/jetbot/worlds/jetbot.wbt
* [x] 235/294: webots/projects/robots/mobsya/thymio/worlds/thymio2.wbt
* [x] 236/294: webots/projects/robots/mobsya/thymio/worlds/thymio2_ball.wbt https://github.com/cyberbotics/webots/issues/3311
* [x] 237/294: webots/projects/robots/mobsya/thymio/worlds/thymio2_pen.wbt https://github.com/cyberbotics/webots/issues/3311
* [x] 238/294: webots/projects/robots/kondo/khr-2hv/worlds/khr-2hv.wbt
* [x] 239/294: webots/projects/robots/kondo/khr-3hv/worlds/khr-3hv.wbt
* [x] 240/294: webots/projects/robots/robotnik/summit_xl_steel/worlds/summit_xl_steel.wbt

Block 5:
* [x] 241/294: webots/projects/robots/neuronics/ipr/worlds/ipr_factory.wbt
* [x] 242/294: webots/projects/robots/neuronics/ipr/worlds/ipr_models.wbt
* [x] 243/294: webots/projects/robots/neuronics/ipr/worlds/ipr_collaboration.wbt
* [x] 244/294: webots/projects/robots/neuronics/ipr/worlds/ipr_cube.wbt
* [x] 245/294: webots/projects/robots/k-team/khepera3/worlds/khepera3.wbt
* [x] 246/294: webots/projects/robots/k-team/khepera3/worlds/khepera3_gripper.wbt
* [x] 247/294: webots/projects/robots/k-team/koala/worlds/koala.wbt
* [x] 248/294: webots/projects/robots/k-team/khepera4/worlds/khepera4.wbt
* [x] 249/294: webots/projects/robots/k-team/khepera1/worlds/khepera_pipe.wbt
* [x] 250/294: webots/projects/robots/k-team/khepera1/worlds/khepera_gripper_camera.wbt
* [x] 251/294: webots/projects/robots/k-team/khepera1/worlds/khepera_k213.wbt
* [x] 252/294: webots/projects/robots/k-team/khepera1/worlds/khepera_gripper.wbt
* [x] 253/294: webots/projects/robots/k-team/khepera1/worlds/khepera.wbt
* [x] 254/294: webots/projects/robots/k-team/khepera1/worlds/khepera_tcpip.wbt
* [x] 255/294: webots/projects/robots/k-team/khepera1/worlds/khepera_kinematic.wbt
* [x] 256/294: webots/projects/robots/k-team/hemisson/worlds/hemisson.wbt
* [x] 257/294: webots/projects/robots/k-team/khepera2/worlds/khepera2.wbt
* [x] 258/294: webots/projects/robots/boston_dynamics/atlas/worlds/atlas.wbt
* [x] 259/294: webots/projects/robots/boston_dynamics/spot/worlds/spot.wbt
* [x] 260/294: webots/projects/robots/rec/fabtino/worlds/fabtino.wbt
* [x] 261/294: webots/projects/robots/parallax/boebot/worlds/boebot.wbt
* [x] 262/294: webots/projects/robots/sphero/bb8/worlds/bb-8.wbt
* [x] 263/294: webots/projects/robots/fp_robotics/p-rob3/worlds/p-rob3.wbt
* [x] 264/294: webots/projects/robots/irobot/create/worlds/create.wbt
* [x] 265/294: webots/projects/robots/saeon/worlds/altino.wbt
* [x] 266/294: webots/projects/robots/robotis/turtlebot/worlds/turtlebot3_burger.wbt
* [x] 267/294: webots/projects/robots/robotis/bioloid/worlds/bioloid_dog.wbt
* [x] 268/294: webots/projects/robots/robotis/darwin-op/worlds/symmetry.wbt
* [ ] 269/294: webots/projects/robots/robotis/darwin-op/worlds/symmetry_matlab.wbt https://github.com/cyberbotics/webots/issues/3357
* [x] 270/294: webots/projects/robots/robotis/darwin-op/worlds/darwin-op.wbt
* [x] 271/294: webots/projects/robots/robotis/darwin-op/worlds/robotis_op3.wbt
* [x] 272/294: webots/projects/robots/robotis/darwin-op/worlds/darwin-op_hinge_vs_hinge2.wbt
* [x] 273/294: webots/projects/robots/robotis/darwin-op/worlds/visual_tracking.wbt
* [x] 274/294: webots/projects/robots/robotis/darwin-op/worlds/motion.wbt
* [x] 275/294: webots/projects/robots/robotis/darwin-op/worlds/soccer.wbt
* [x] 276/294: webots/projects/robots/robotis/darwin-op/worlds/walk.wbt
* [x] 277/294: webots/projects/robots/nasa/worlds/sojourner.wbt
* [x] 278/294: webots/projects/robots/niryo/ned/worlds/ned.wbt
* [x] 279/294: webots/projects/robots/universal_robots/worlds/ure.wbt
* [x] 280/294: webots/projects/robots/epfl/biorob/worlds/salamander.wbt
* [x] 281/294: webots/projects/robots/epfl/biorob/worlds/ghostdog.wbt
* [x] 282/294: webots/projects/robots/epfl/biorob/worlds/yamor.wbt
* [x] 283/294: webots/projects/robots/epfl/lis/worlds/blimp.wbt
* [x] 284/294: webots/projects/robots/clearpath/pr2/worlds/pr2.wbt
* [x] 285/294: webots/projects/robots/clearpath/moose/worlds/moose_demo.wbt
* [x] 286/294: webots/projects/robots/dji/mavic/worlds/mavic_2_pro.wbt
* [x] 287/294: webots/projects/robots/surveyor/worlds/srv-1.wbt
* [x] 288/294: webots/projects/robots/a4/portal/worlds/portal_pe.wbt
* [x] 289/294: webots/projects/robots/lego/mindstorms/worlds/rover.wbt
* [x] 290/294: webots/projects/robots/picaxe/microbot/worlds/microbot_pe.wbt
* [x] 291/294: webots/projects/robots/abb/irb/worlds/inverse_kinematics.wbt
* [x] 292/294: webots/projects/robots/unimation/puma/worlds/puma560.wbt
* [x] 293/294: webots/projects/robots/fujitsu/hoap2/worlds/hoap2_sumo.wbt
* [x] 294/294: webots/projects/robots/fujitsu/hoap2/worlds/hoap2_walk.wbt
* [x] webots-projects jetbot
* [ ] webots-projects seronet

**Comment by stefaniapedrazzi** [comment]
Here is how we could split the blocks of worlds:
* @omichel: block 1
* @stefaniapedrazzi block 2
* @mael25 block 3
* @ad-daniel block 4
*  @lukicdarkoo block 5
